D0_max_pt: 100
D0_min_pt: 3.0
D0mode: 1
write_parts: true
parts_select_final: true
parts_select_charged: false
config: null
debug: false
init_dict: null
init_ignore_none: true
init_json: null
init_yaml: null
jet_R: 0.4
jet_pt_max: -1
jet_pt_min: 20.0
log: false
part_abs_eta_max: 20
jet_abs_eta_max: 20
jet_eta_min: null
jet_eta_max: null
ncounts: -1
nev: -1
output: eec_pythia8.root
py_PbPb: false
py_bias: false
py_biaspow: 4
py_biasref: 10
py_cmnd_out: Pythia8.cmnd
py_diff: false
py_dire: false
py_ecm: 5000.0
py_ecms: low
py_eic: false
py_eic_bgamma: false
py_eic_cgamma: false
py_eic_dis: false
py_eic_lowQ2: false
py_eic_qgamma: false
py_eic_test: false
py_el: false
py_hadronization_off: false
py_hardQCD: true
py_hardQCDbeauty: false
py_hardQCDcharm: false
py_hardQCDgluons: false
py_hardQCDlf: false
py_hardQCDquarks: false
py_hardQCDuds: false
py_inel: false
py_inel_d: false
py_inel_nsd: false
py_minbias: false
py_n: 1
py_nd: false
py_noHadron: false
py_noISR: false
py_noMPI: false
py_noue: false
py_nsd: false
py_promptPhoton: false
py_pthatmax: -1
py_pthatmin: -1
py_seed: -1
py_time_seed: false
py_vincia: false
pythiaopts: ''
verbose: false
write_config: ''
